In [1]:
import numpy as np

# Datos: 4 filas (muestras) y 3 columnas (características)
datos = np.array([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90],
                  [100, 110, 120]])

# Pesos: Un vector de 3 elementos (uno para cada columna)
pesos = np.array([0.5, 1.2, 0.8])

# Operación de Broadcasting
resultado = datos * pesos

print("Matriz original (4, 3):\n", datos)
print("\nVector de pesos (3,):\n", pesos)
print("\nResultado (Broadcasting aplicado):\n", resultado)

# EXPLICACIÓN:
# El vector 'pesos' tiene forma (3,). NumPy lo "estira" virtualmente
# para que coincida con la forma de 'datos' (4, 3), repitiendo el vector 
# en cada una de las 4 filas.

Matriz original (4, 3):
 [[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]

Vector de pesos (3,):
 [0.5 1.2 0.8]

Resultado (Broadcasting aplicado):
 [[  5.  24.  24.]
 [ 20.  60.  48.]
 [ 35.  96.  72.]
 [ 50. 132.  96.]]


In [2]:
# Matriz de calificaciones: 3 alumnos (filas), 4 materias (columnas)
calificaciones = np.array([[8, 9, 7, 10],
                           [6, 5, 8, 7],
                           [9, 9, 10, 9]])

# Calculamos la media de cada ALUMNO (media por fila)
# Usamos keepdims=True para que el resultado sea (3, 1) en lugar de (3,)
medias_filas = np.mean(calificaciones, axis=1, keepdims=True)

# Restamos la media a cada nota (Estandarización)
calificaciones_centradas = calificaciones - medias_filas

print("Medias por fila (forma 3x1):\n", medias_filas)
print("\nCalificaciones centradas:\n", calificaciones_centradas)

# EXPLICACIÓN:
# La matriz es (3, 4) y la media es (3, 1). 
# El broadcasting funciona porque la dimensión de tamaño 1 se estira 
# a lo largo de las 4 columnas para poder realizar la resta.

Medias por fila (forma 3x1):
 [[8.5 ]
 [6.5 ]
 [9.25]]

Calificaciones centradas:
 [[-0.5   0.5  -1.5   1.5 ]
 [-0.5  -1.5   1.5   0.5 ]
 [-0.25 -0.25  0.75 -0.25]]


In [3]:
# Creamos dos vectores de coordenadas
x = np.linspace(0, 5, 6) # [0, 1, 2, 3, 4, 5]
y = np.linspace(0, 3, 4) # [0, 1, 2, 3]

# Cambiamos las formas para forzar el broadcasting
# X será una fila (1, 6) y Y será una columna (4, 1)
X = x.reshape(1, 6)
Y = y.reshape(4, 1)

# Evaluamos f(X, Y) = X + Y
# Esto crea una tabla de sumar (malla)
malla_suma = X + Y

print("Vector X (forma 1x6):\n", X)
print("\nVector Y (forma 4x1):\n", Y)
print("\nMalla resultante f(X,Y) = X + Y (forma 4x6):\n", malla_suma)

# EXPLICACIÓN:
# X (1, 6) y Y (4, 1) son compatibles. NumPy expande X a (4, 6) 
# y expande Y a (4, 6), sumándolos elemento a elemento para cubrir 
# todas las combinaciones posibles de coordenadas.

Vector X (forma 1x6):
 [[0. 1. 2. 3. 4. 5.]]

Vector Y (forma 4x1):
 [[0.]
 [1.]
 [2.]
 [3.]]

Malla resultante f(X,Y) = X + Y (forma 4x6):
 [[0. 1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5. 6.]
 [2. 3. 4. 5. 6. 7.]
 [3. 4. 5. 6. 7. 8.]]
