In [1]:
import numpy as np

# 1. Crear array desde una lista
arr_lista = np.array([1, 2, 3, 4, 5])

# 2. Array de ceros y unos
ceros = np.zeros((3, 3)) # Matriz 3x3 de ceros
unos = np.ones((2, 5))   # Matriz 2x5 de unos

# 3. Array con un rango (similar al range de Python)
rango = np.arange(0, 10, 2) # De 0 a 10 de 2 en 2

# 4. Array con valores aleatorios
aleatorios = np.random.rand(3, 2) # Matriz 3x2 con valores entre 0 y 1

print("Array de ceros:\n", ceros)
print("\nArray aleatorio:\n", aleatorios)

Array de ceros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Array aleatorio:
 [[0.65714649 0.85129812]
 [0.26695886 0.90846074]
 [0.3397181  0.4184578 ]]


In [2]:
import time

# Ejemplo de facilidad de operación
lista = [1, 2, 3]
try:
    print(lista + 1) # Esto dará error en listas
except TypeError:
    print("❌ Las listas no permiten sumar un escalar directamente.")

# En NumPy es directo y rápido
arr = np.array([1, 2, 3])
print("✅ Operación en NumPy (arr + 10):", arr + 10)

# Ejemplo de eficiencia (Multiplicar 1 millón de elementos)
size = 1000000
l1 = list(range(size))
a1 = np.arange(size)

start = time.time()
l_res = [x * 2 for x in l1]
print(f"\nTiempo con lista: {time.time() - start:.5f} seg")

start = time.time()
a_res = a1 * 2
print(f"Tiempo con NumPy: {time.time() - start:.5f} seg")

❌ Las listas no permiten sumar un escalar directamente.
✅ Operación en NumPy (arr + 10): [11 12 13]

Tiempo con lista: 0.06780 seg
Tiempo con NumPy: 0.00363 seg


In [4]:
# Creamos una matriz 2D para el ejemplo
matriz = np.array([[1, 2, 3], [4, 5, 6]])

print(f"Matriz:\n{matriz}")
print("-" * 20)
print(f"1. Dimensión (ndim): {matriz.ndim}")     # Cuántas dimensiones tiene
print(f"2. Forma (shape): {matriz.shape}")       # Filas y columnas (2, 3)
print(f"3. Total elementos (size): {matriz.size}") # Cuántos datos hay en total
print(f"4. Tipo de dato (dtype): {matriz.dtype}")  # Tipo de los elementos (int, float, etc)

Matriz:
[[1 2 3]
 [4 5 6]]
--------------------
1. Dimensión (ndim): 2
2. Forma (shape): (2, 3)
3. Total elementos (size): 6
4. Tipo de dato (dtype): int64
