In [1]:
import numpy as np

# Fijamos la semilla para reproducibilidad
np.random.seed(42)

print("--- 1. ESTADÍSTICAS DE CONJUNTOS ALEATORIOS ---")

# Generamos 5 conjuntos con diferentes distribuciones y tamaños
datasets = {
    "Normal (100)": np.random.randn(100),
    "Enteros (50)": np.random.randint(1, 101, 50),
    "Uniformes (80)": np.random.rand(80),
    "Grandes (1000)": np.random.normal(50, 10, 1000),
    "Pequeños (10)": np.random.randint(1, 10, 10)
}

print(f"{'Dataset':<15} | {'Media':<8} | {'Mediana':<8} | {'Desv. Est':<10}")
print("-" * 50)

for nombre, data in datasets.items():
    media = np.mean(data)
    mediana = np.median(data)
    desv = np.std(data)
    print(f"{nombre:<15} | {media:8.2f} | {mediana:8.2f} | {desv:10.2f}")

--- 1. ESTADÍSTICAS DE CONJUNTOS ALEATORIOS ---
Dataset         | Media    | Mediana  | Desv. Est 
--------------------------------------------------
Normal (100)    |    -0.10 |    -0.13 |       0.90
Enteros (50)    |    51.66 |    54.50 |      29.89
Uniformes (80)  |     0.50 |     0.55 |       0.29
Grandes (1000)  |    50.21 |    50.34 |      10.01
Pequeños (10)   |     6.70 |     8.00 |       2.53


In [2]:
print("--- 2. ANÁLISIS POR EJES (AXIS) ---")

matriz = np.random.randint(1, 100, (5, 5))
print("Matriz Original:\n", matriz)

# Operaciones por columnas (Vertical - axis 0)
print("\nAnálisis por COLUMNAS (axis=0):")
print("Suma:", np.sum(matriz, axis=0))
print("Media:", np.mean(matriz, axis=0))
print("Mínimo:", np.min(matriz, axis=0))

# Operaciones por filas (Horizontal - axis 1)
print("\nAnálisis por FILAS (axis=1):")
print("Suma:", np.sum(matriz, axis=1))
print("Máximo:", np.max(matriz, axis=1))

--- 2. ANÁLISIS POR EJES (AXIS) ---
Matriz Original:
 [[50 24 19 60 39]
 [74 89 18 19 36]
 [74 97 55 69 47]
 [49 99 98 33 21]
 [81 22 48 37 15]]

Análisis por COLUMNAS (axis=0):
Suma: [328 331 238 218 158]
Media: [65.6 66.2 47.6 43.6 31.6]
Mínimo: [49 22 18 19 15]

Análisis por FILAS (axis=1):
Suma: [192 236 342 300 203]
Máximo: [60 89 97 99 81]


In [4]:
print("--- 3. SIMULACIÓN DE 1,000 LANZAMIENTOS DE DADO ---")

lanzamientos = np.random.randint(1, 7, 1000) # Números del 1 al 6

print(f"{'Cara':<10} | {'Frecuencia':<12} | {'Porcentaje':<10}")
print("-" * 35)

for cara in range(1, 7):
    conteo = np.count_nonzero(lanzamientos == cara)
    porcentaje = (conteo / 1000) * 100
    print(f"Lado {cara:<5} | {conteo:<12} | {porcentaje:.2f}%")

--- 3. SIMULACIÓN DE 1,000 LANZAMIENTOS DE DADO ---
Cara       | Frecuencia   | Porcentaje
-----------------------------------
Lado 1     | 172          | 17.20%
Lado 2     | 150          | 15.00%
Lado 3     | 171          | 17.10%
Lado 4     | 174          | 17.40%
Lado 5     | 182          | 18.20%
Lado 6     | 151          | 15.10%
